apiVersion: skaffold/v4beta8
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: mises/exam-service
      context: ExamService
      docker:
        dockerfile: Dockerfile
    - image: mises/word-service
      context: WordService
      docker:
        dockerfile: Dockerfile
    - image: mises/web-service
      context: WebService
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "frontend/dist/index.html"
            dest: .
          - src: "frontend/assets/*.*"
            dest: .
deploy:
  kubectl:
    remoteManifests:
      - ./k8s/*
