apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: exam-service
  template:
    metadata:
      labels:
        component: exam-service
    spec:
      containers:
        - name: exam-service
          image: mises/exam-service
          ports:
            - containerPort: 8090
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: learn-english-secret
                  key: MONGODB_URI
            - name: DATABASE_NAME
              value: Test_LearnEnglishMicroservices
            - name: SERVER_ADDRESS
              value: :8090
