apiVersion: apps/v1
kind: Deployment
metadata:
  name: word-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: word-service
  template:
    metadata:
      labels:
        component: word-service
    spec:
      containers:
        - name: word-service
          image: mises/word-service
          ports:
            - containerPort: 8091
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: learn-english-secret
                  key: MONGODB_URI
            - name: DATABASE_NAME
              value: Test_LearnEnglishMicroservices
            - name: SERVER_ADDRESS
              value: :8091
