# For exam_handler_integration_test.go
services:
  mongodb:
    image: mongo:6
    ports:
      - 27017:27017
  exam-service:
    image: mises/exam-service:test
    environment:
      MONGODB_URI: mongodb://mongodb:27017
      DATABASE_NAME: Test_LearnEnglish
      SERVER_ADDRESS: :8090
    ports:
      - 8090:8090
